### ISSUE TITLE
Hardcoded

### ISSUE THREAD

**Issue by ghost** [Yonle/installevery_termuxpackage#2]
Exactly what it says

**Comment by Yonle** [comment]
Hi. Sorry for the late response.

The shell code is originally generated by one of my code by reading package list that came from `apt list` into generated script. However, it's **still** readable and very easy to understood.

**Comment by ghost** [comment]
So you mean it is not possible to list them with `apt`? (It does show a warning of `apt` to not run in a script)

**Comment by Yonle** [comment]
It's possible to list them.

I just generate the command. So this is what i mean:

```
# To generate, i must parse the package list in "apt list". 
# Then we generate it like this:
apt install [parsed_pkg_list]

# Like:
apt install 0verkill 8086tiny # .......
```

**Comment by ghost** [comment]
The problem is you have to update it whenever a package exists/removed.

**Comment by Yonle** [comment]
Nah. I'm no longer update this repo anyway. PR is still welcome.
